name: Nickplaysmusic
favicon: null
layout_spectrum: 0.49625
typography_spectrum: 0.7959900721907616
title: Nick Plays Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1217'
    - '#fefeff'
    - '#f69a18'
    - '#24557d'
    - '#899cb0'
  brandStrength: 0.9128883415833116
  lightness: 0.5819326813798398
  saturation: 0.34878444857895374
  rhythmicContrast: 0.48575218254700303
purpose: []
